### PR TITLE
add screenshot

### PR DESCRIPTION
**Pull request by NonglongSu**

### CODE REVIEW

**Comment by dmgt** [comment]
Hi, thanks for adding to the [collaborative doc](https://hackmd.io/SGRP3O3CSoOORDDQfpMlow#) earlier today - feel free to keep adding your questions and suggestions! 

This looks like a picture of the hackmd pad (which has since changed), were you thinking it'd specifically be helpful to have this image in some part of the Binder tutorial doc, were you testing making a PR, or did you have something else in mind?

**Comment by NonglongSu** [comment]
Hi Dana,
    I was just testing the example so I made a screenshot. There is no
special meanings about that. Sorry if that confused u.

Best
Ziqi

**Comment by dmgt** [comment]
Thanks for clarifying, in that case will go ahead and close this PR.

**Comment by NonglongSu** [comment]
Sure. Thanks. And thanks for the experience sharing of Singapore.

Best

**Pull request closed without merging**
